# slam_toolbox:
#   ros__parameters:
#     use_sim_time: true
#     base_frame: base_link
#     odom_frame: odom
#     map_frame: map

slam_toolbox:
  ros__parameters:

    # --- Minimum params:
    # Simulation
    use_sim_time: true

    # Frame names
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    
    # ---- Extras: 
    # Scan processing
    scan_topic: /scan
    scan_buffer_size: 10
    
    # Loop closure
    use_scan_matching: true
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    
    # Map resolution
    resolution: 0.05
    
    # SLAM parameters
    max_laser_range: 10.0
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.174  # 10 degrees in radians