explore_node:
  ros__parameters:
    robot_base_frame: base_link
    use_sim_time: true  # Added
    global_frame: map   # Added
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: /global_costmap/costmap_updates
    visualize: true
    # planner_frequency: 0.15
    planner_frequency: 0.25    # Hz
    # progress_timeout: 30.0
    progress_timeout: 120.0
    # potential_scale: 3.0
    potential_scale: 1.0
    orientation_scale: 0.0
    # gain_scale: 1.0
    gain_scale: 0.5
    # transform_tolerance: 0.3
    transform_tolerance: 1.0
    # min_frontier_size: 0.5
    min_frontier_size: 0.4
    goal_aliasing_distance: 0.3   # keeps frontiers/goals spaced from walls & each other
    goal_blacklist_timeout: 60.0  # Allow retry of "failed" goals